### ISSUE TITLE
Parkour improvements

### ISSUE THREAD

**Issue by ShibaMiyuk1** [NameTaken3125/ACUFixes#2] opened 2023-05-15 13:58 UTC
Can you add any of parkour improvements with in-game animations like a spining controlled decend with pressing a key to do it anywhere or something another i thing it would be a good improvement for a game i help you with this if its possible
https://www.youtube.com/shorts/GZihVfDPlqA - video of controlled decend animation

**Comment by NameTaken3125** [comment] 2023-05-20 08:59
Duplicate of #1, also see [Version 0.3.0](https://github.com/NameTaken3125/ACUFixes/releases/tag/v0.3.0) for my solution

**Closed by NameTaken3125** 2023-05-20 08:59 UTC
